/**
 * The "rules that will bite you" bank.
 *
 * Data, not prose: each rule has a stable id so a brief can cite it and a test
 * can assert the citation still resolves. Each rule was established by reading
 * the upstream repository and its first-party plugins.
 */

export const RULES: Readonly<Record<string, string>> = Object.freeze({
  "frontend-no-network": "The frontend has no network plane of its own. Call your server entry through `useRpc` → `bb.rpc`; never `fetch` from `app.tsx`.",
  "shims-devdeps": "React, the SDK and every shimmed package (sonner, vaul, radix, @pierre/diffs, clsx, tailwind-merge, cva) come from the host at runtime. They belong in `devDependencies` — putting one in `dependencies` bundles a second copy and breaks the plugin.",
  "replacement-original": "bb passes `Original`. Render it to delegate — that is the supported way to handle the cases you do not want to own.",
  "exclusive-slot": "Only one plugin can own this at a time; the user picks the winner in Settings → Appearance. Do not assume yours is active.",
  "crash-boundary": "Each slot is wrapped in its own error boundary. A crash shows a chip and the rest of bb keeps working — but the crash is sticky for the session, so fix it rather than relying on the fallback.",
  "css-scope": "Your styles are scoped to `:where([data-bb-plugin=<id>],[data-bb-plugin-root]:not([data-bb-plugin]))`. Only default-theme Tailwind utilities are emitted; custom `@theme` colors and hand-written `oklch(...)` literals will not survive the build.",
  "icons-hugeicons": "Icon names are bb's own set (hugeicons), not lucide. A plugin-owned glyph is declared in `bb.branding.experimental_icons` and referenced as `\"<pluginId>/<name>\"`.",
  "backend-full-trust": "Plugins are full-trust code inside the server process: they can read all local bb data, including other plugins' secrets. `secret: true` settings are plaintext files with mode 0600, not encrypted. Design accordingly.",
  "secrets-agent-reach": "An agent shell running as the same user on the same machine can read your plugin's data and secrets, and the local API is unauthenticated. If a capability must not be triggered by the agent alone, split it: the agent proposes, a human confirms through `bb.ui.requestInput`.",
  "experimental-churn": "Every `experimental_` member is in `docs/api_to_audit.md` and gets renamed project-wide when it stabilizes. Compatibility aliases warn for one release and then throw.",
  "tool-output-bounded": "Return bounded output — `PLUGIN_CLI_OUTPUT_MAX_BYTES` caps CLI output and oversized tool results get truncated.",
  "interaction-detached": "`bb.ui.requestInput` survives the end of the agent's turn: the answer arrives later as a system message. Handle `cancelled` with all of its reasons (user, request-aborted, thread-stopped, thread-deleted, plugin-disposed, server-restarted, timeout).",
  "dispose-lifo": "The factory is time-boxed at 30 s and its return value is discarded. Register cleanup with `bb.onDispose` (LIFO) — services, schedules, listeners, content scripts, everything.",
  "panel-params-untrusted": "Panel `params` round-trip through persistence, so treat them as untrusted input: re-fetch fresh data by id instead of embedding whole payloads.",
  "directive-attrs-untrusted": "Directive attributes are untrusted strings parsed out of the message. Validate your own fields; anything malformed falls back to rendering the original source text.",
  "thread-list-keyboard": "Row anchors must carry `data-sidebar-thread-shortcut-target=\"\"` and `data-sidebar-thread-id={thread.id}`, or bb's `thread.next` / `thread.previous` shortcuts silently stop working.",
  "content-script-trust": "A content script is trusted, same-origin page code — not a sandbox. It runs once per window, tab and remote client, and everything it touches must be released through the abort signal or the returned disposer.",
  "mount-timeout": "Async mount setup is time-boxed at 10 s. A throwing or slow mount aborts the candidate generation, disposes what already mounted in reverse and publishes nothing.",
  "header-geometry": "The thread header is a 48 px chrome row with 28 px controls: render one inline control and portal anything taller.",
  "split-instances": "A split layout mounts one instance per visible pane. Never keep per-thread state in a module-level singleton.",
  "browser-page-null": "`experimental_page` is null outside the desktop app, and it takes no CDP control lease — no control banner appears. The `isolated` world shares the DOM but not page globals.",
  "timeline-kind-ownership": "You may only render your own extension kinds (`\"<pluginId>/<name>\"`) and `\"tool\"` rows of providers your plugin registered. Core kinds always use core renderers.",
  "message-reference": "`ThreadChatMessageReference` is a narrow stable reference, never an internal timeline row; `sourceSeqEnd` is the anchor the server accepts for provider-history forks.",
  "interaction-limits": "Hard limits: title 1–160 chars, payload ≤64 KiB of JSON, `timeoutMs` default 10 min and capped at 1 hour. bb stores neither the payload nor the submitted value — only what `describeSubmission` returns.",
  "diff-patch-complete": "`patch` is always a complete single-file unified patch whatever the caller supplied. Verify paths and hunk lines agree before treating `experimental_fullFileContents` as complete.",
  "file-source-kinds": "`path` semantics follow `source.kind`: worktree-relative for `workspace`, absolute for `host`, storage-relative for `thread-storage`.",
  "overlay-owns-chrome": "bb supplies no chrome, positioning or visibility for an overlay: it mounts once per app window and you own everything it draws.",
  "composer-scopes": "Declare `scopes` deliberately: `thread`, `queued-message`, `side-chat` and `new-thread` behave differently, and some (queued-message, side chat) have no submit pipeline at all.",
  "composer-submit-pipeline": "Submit through `composer.experimental_submit(...)`, not your own request: the draft's attachments, @-mentions and (in new-thread) provider/model/reasoning/tier/permission/environment selections only travel that way.",
  "composer-inline-cap": "bb keeps at most three plugin inline actions in the control row, ranked by use; the rest move into an overflow menu.",
  "composer-scoped-effects": "`setTextEffect` and `setInputLock` are scoped to your plugin and auto-release when your slot unmounts or the composer scope changes.",
  "composer-write-target": "Writes land in the composer that mounted your slot: the queued-message editor, the visible side-chat draft, the thread draft, or otherwise the new-thread draft — which persists until the user sends or clears it.",
  "richtext-paint-only": "Rich-text effects are paint-only: they never mutate the draft, and offsets are plain-text offsets into the current structured draft.",
  "command-shortcuts": "A `defaultShortcut` is validated strictly: bare modifiers are rejected and Command/Control/Alt or an F1–F24 key is required. User overrides live under `plugin:<plugin-id>/<command-id>`.",
  "command-isavailable": "`isAvailable` runs before listing and before keyboard invocation — keep it cheap and synchronous; errors are contained.",
  "engines-gate": "Declare the floor you rely on in `engines.bbPluginSdk` (`app.commands.register` needs `>=0.4.91`, keyboard bindings `>=0.4.92`). Managed installs refuse a plugin whose SDK is newer than the host.",
  "mention-search-timebox": "`search` runs on the server, is time-boxed to 2 s and is failure-isolated: a slow or throwing provider simply contributes nothing.",
  "mention-resolve-blocks": "`resolve` runs once per unique item at send time and a throw blocks the send with a visible error. Item ids are namespaced by the host as `\"<providerId>:<itemId>\"`.",
  "mention-images-untrusted": "Treat remote and page-derived image content attached through `experimental_images` as untrusted evidence.",
  "settings-load-once": "Settings are read once per load. Saving does not reload the plugin in V1 — tell the user to run `bb plugin reload <id>`, or subscribe with `onChange`.",
  "settings-secrets": "Only string settings can be `secret: true`; secrets are never sent to the frontend (`useSettings()` sees non-secret values only) and never stored in the database.",
  "status-cleared-on-load": "`needsConfiguration` is cleared on the next load, so re-report it from the factory on every load while the configuration is still missing.",
  "needs-configuration-error": "`NeedsConfigurationError` is matched by name — `throw Object.assign(new Error(msg), { name: \"NeedsConfigurationError\" })` — so a service can mark the plugin instead of crash-looping.",
  "cli-runs-on-server": "The CLI handler runs inside the server process, not in the CLI: `argv` excludes the command name and `ctx.signal` aborts when the invoking request disconnects.",
  "cli-output-cap": "`PLUGIN_CLI_OUTPUT_MAX_BYTES` is 1 MiB of stdout + stderr combined, and the host rejects an oversized result atomically instead of clipping it.",
  "cli-argv": "Core bb commands always win a name collision; your plugin stays reachable as `bb plugin run <id>`. Use `defineCli` so `--help`, unknown-flag hints and `--json` envelopes come for free.",
  "tools-next-session": "A changed tool set or changed instructions take effect only when the provider session is next started or resumed — bb never hot-mutates a running session.",
  "tool-name-global": "Tool names are unique across plugins. A collision is not fatal: the later tool is dropped and the reason lands in your plugin's status detail.",
  "instructions-cap": "Tool `instructions` and every instruction contribution are capped at 4096 characters; `configure` selections are capped at 256 ids.",
  "rpc-strict-json": "RPC results must be strict JSON: cycles, bigint, `undefined`, functions, class instances, symbol keys and non-finite numbers are rejected, not coerced.",
  "http-exact-match": "HTTP routes are exact-match under `/api/v1/plugins/<id>/http`: `:` and `*` are literal characters. `auth: \"none\"` is only for webhooks that verify their own signature.",
  "realtime-broadcast": "`bb.realtime.publish` broadcasts to every connected client and nothing is persisted or replayed — it is not a confidentiality boundary, and durable state must be reconciled on later `connected` transitions.",
  "events-are-announcements": "Events are announcements: the return value is ignored and a handler can never block or veto the change. The surface that can decide is `bb.experimental_hooks`.",
  "events-see-everything": "Every listener sees every row, including other plugins'. Filter on `entry.waitingOn?.kind === \"plugin\" && entry.waitingOn.pluginId === bb.pluginId`.",
  "message-cancelled-only-signal": "`message.cancelled` is the only signal that a queued row was removed before it ever dispatched.",
  "hook-fail-closed": "The dispatch hook is fail-closed: a handler that throws or exceeds the 10 s decision box fails the attempt with your plugin named. Decide in milliseconds.",
  "hook-idempotent": "The pass re-runs on every drain, restart and retry, so a handler must be idempotent for one logical dispatch.",
  "hook-no-amendment": "There is no \"handled it myself\" answer and no amendment arm: a hook decides (proceed / wait / reject), it never rewrites the dispatch.",
  "send-now-bypass": "A user's explicit Send-now bypasses the pass by design, as do compaction and an edited message's re-send.",
  "service-abort-sleep": "A service must resolve when its `signal` aborts — a plain `setTimeout` sleeps through the stop window and the plugin reports \"degraded (service did not stop)\" on reload.",
  "schedule-only-while-loaded": "A cron schedule fires only while the plugin is loaded, so anything that must survive a disable needs its own startup reconciliation.",
  "kv-value-cap": "`bb.storage.kv` values are JSON capped at 256 KB each; anything bigger or relational belongs in `bb.storage.database()`.",
  "migrations-append-only": "Migrations are append-only by index: the host records each statement's hash and rejects a changed or reused index.",
  "storage-not-a-boundary": "Storage isolation is a convention of the `bb.storage` helpers, not an enforced boundary — another plugin can open your `data.db` with ordinary `fs`.",
  "sdk-bind-gated": "`bb.sdk` is bind-gated: reading it before the host binds it throws. Prefer using it from handlers, services and timers so isolated harnesses behave the same.",
  "sdk-hidden-threads": "Hidden worker threads need explicit cleanup — stop and archive them in a `finally` so a plugin failure cannot retain the agent process.",
  "sdk-attribution": "`threads.spawn` / `threads.fork` default `origin` to `\"plugin\"` and `originPluginId` to your id; seeding `pluginMetadata` always attributes the new thread to you.",
  "metadata-untrusted": "Namespace ids are not an ownership or authorization boundary: any API client, another plugin or the thread's own agent can write any namespace. Treat values as untrusted input.",
  "metadata-size": "Each namespace caps at 256 KiB of UTF-8 JSON; an over-size patch fails with HTTP 413 and leaves the namespace unchanged.",
  "metadata-frozen-in-configure": "Inside `bb.agents.configure` the namespace arrives deep-frozen — copy it before handing values to anything that expects mutable `JsonValue`.",
  "provider-needs-host": "Registering a provider without a `bb.host` entry fails the plugin load: the bridge ships in the host artifact.",
  "provider-id-immutable": "A provider `id` is persisted on every thread that used it — never change it. Ids are flat and collision-rejected across plugins.",
  "provider-derive-sync": "`deriveProviderOptions` is synchronous, runs on every session and turn command and is capped at 64 KiB; a throw fails the command with your plugin named.",
  "bridge-grammar-v3": "The delta assembler speaks grammar v3 only. Every turn needs `input.accepted` → `turn.open` → deltas → `turn.boundary`, even a zero-work prompt.",
  "env-create-idempotent": "`create` is one long call and must be idempotent for its `pathKey`: after a restart core calls it again with the same attempt and pathKey.",
  "env-failure-terminal": "A failed create is terminal — there is no automatic retry ladder. Return `{ status: \"failed\", message }` with user-safe recovery copy.",
  "env-inputs-public": "Parsed `inputs` are persisted and readable by every plugin, including after the environment is destroyed. They are configuration, not a credential store.",
  "env-hooks-owned-by-core": "Core runs `.bb-env-setup.sh` after a create that returns `ownsPath: true` and `.bb-env-teardown.sh` before remove. Providers must not call these hooks themselves.",
  "machine-checkpoint": "`await checkpoint(resource)` after durable allocation and before bootstrap, and never put the bootstrap bundle in the resource JSON.",
  "machine-needs-composition": "Registering a machine provider contributes no environment-picker entry: also register a composition naming `machineProviderId` + `environmentProviderId`.",
  "machine-resource-public": "`inputs`, `resource` and every `report.step` / `report.log` line are persisted and readable by other plugins and copied into thread transcripts. Store references, never secrets.",
  "machine-idle-is-yours": "Idle timing is the plugin's, not core's: watch activity events and sweep with a schedule plus startup reconciliation.",
  "access-acquire-idempotent": "`acquire` is idempotent by key and must persist the revocation identity before returning, so `release` works even before enrolment completes.",
  "access-release-null-grant": "`release` receives a null `grantId` when acquisition was interrupted — reconcile by key and hostId.",
  "host-call-not-in-factory": "Create the client and register signal handlers in the factory, but call host methods only from an RPC/event handler, background service or timer — candidate-time calls are rejected.",
  "host-no-private-imports": "A host artifact may not import bb's private `@bb/*` packages at all, and it is fully self-contained: pure-JS dependencies are bundled into `dist/host.js`.",
  "host-limits": "Host RPC limits: 32 MiB in, 8 MiB out, 30 s default timeout capped at 30 minutes, worker start 10 s, idle eviction after 5 minutes unless retained.",
  "host-worker-exit": "`experimental_onWorkerExit` fires only on unexpected exits: graceful reload, disable, uninstall, daemon shutdown and idle eviction are silent.",
  "browser-lease-ttl": "Control leases really expire: clamp your session's own expiry to the minimum of your TTL, the lease's and the connection's.",
  "browser-allow-personal": "Pass `allowPersonal: true` only when the user explicitly picked an existing tab, and close only the tabs your plugin created.",
  "browser-host-match": "Treat a connection whose `hostId` differs from your scope as fatal — the CDP endpoint is host-scoped.",
  "ai-needs-host": "An AI service must declare a `bb.host` entry; registering without one fails the load, and core always calls the primary host.",
  "ai-failures-returned": "Return failures as `{ ok: false, code }` instead of throwing, so core can apply its retry and fallback policy (timeouts and rate limits fall back; auth failures do not).",
  "ai-reserved-ids": "Ids the server serves itself (`openai` transcription and the built-in inference providers) are reserved and refused.",
  "jsx-alias-experimental": "JSX reads a lowercase-initial name as an intrinsic element, so import `experimental_*` components under an aliased capitalised name (`experimental_Diff as Diff`).",
  "threadchat-owns-thread": "`ThreadChat` owns timeline loading, streaming, drafts, send/queue/steer/stop, attachments and pending interactions — do not proxy thread data through your own RPC.",
  "no-worker-pool": "`experimental_Diff` takes the host's shared highlight worker pool from React context: thread and nav panels have one, homepage and settings sections do not, so code there renders unhighlighted.",
  "harness-same-collector": "`loadPluginApp` runs the same validating collector as the host with the same error messages — pass the thunk form `() => import(\"./app\")` so the module evaluates after the runtime is installed.",
  "harness-stubs": "Host components in the frontend harness are prop-recording stubs, not the real engines, and the harness composer has no submit pipeline.",
});

export type RuleId = keyof typeof RULES;

export function ruleText(id: string): string {
  const text = RULES[id];
  if (text === undefined) throw new Error(`Unknown rule id: ${id}`);
  return text;
}

export function ruleIds(): string[] {
  return Object.keys(RULES).sort();
}
